config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", :as => :rails_health_check

  root "crosswords#index"

  get "/:number", to: "crosswords#show", as: :crossword, constraints: {number: /\d.+/}

  get "/about", to: "pages#about", as: :about_page
  get "/settings", to: "pages#settings", as: :settings_page

  resource "sync", only: [:new, :create, :show], controller: :sync, as: :sync do
    resource :device, only: [:create, :destroy], controller: "sync/device", as: :device
  end
  get "/sync/device", to: "sync/device#new", as: :new_sync_device

  resources :answers, only: [:update]

  mount MissionControl::Jobs::Engine, at: "/jobs"

  namespace :admin do
    resources :crosswords
    resources :answers
    resources :accounts
    resources :imports

    root to: "crosswords#index"
  end

  resource :devmode, only: [:show, :destroy], controller: :devmode

  match "*unmatched", to: "application#not_found", via: :all
end

app/controllers/sync/device_controller.rb
module Sync
  class DeviceController < ApplicationController
    rate_limit to: 3, within: 1.minute, only: [:create]

    before_action :redirect_if_syncing, only: [:new, :create]

    layout "page"

    def new
      @account = Account.new
    end

    def create
      account = Account.find_by!(key: account_params[:key].downcase.strip)
      self.current_account = account.id

      redirect_to sync_path, notice: "Syncing enabled"
    rescue ActiveRecord::RecordNotFound
      @account = Account.new
      @account.errors.add(:base, "Invalid sync key")
      render :new, status: :unprocessable_entity
    end

    def destroy
      cookies.delete(:current_account_id)
      Current.account = nil

      redirect_to root_path, notice: "Syncing disabled", status: :see_other
    end

    private

    def account_params
      params.require(:account).permit(:key)
    end
  end
end

app/controllers/sync/link_controller.rb
module Sync
  class LinkController < ApplicationController
    rate_limit to: 3, within: 1.minute, only: [:create]

    before_action :ensure_devmode
    before_action :redirect_if_syncing, only: [:new, :create]

    layout "page"

    def new
      @account = Account.new
    end

    def create
      account = Account.find_by!(key: account_params[:key].downcase)
      session[:current_account_id] = account.id

      redirect_to sync_path, notice: "Syncing enabled"
    rescue ActiveRecord::RecordNotFound
      @account = Account.new
      @account.errors.add(:base, "Invalid sync key")
      render :new, status: :unprocessable_entity
    end

    def destroy
      session.delete(:current_account_id)
      Current.account = nil

      redirect_to new_sync_path, notice: "Syncing disabled", status: :see_other
    end

    private

    def account_params
      params.require(:account).permit(:key)
    end
  end
end

app/controllers/sync_controller.rb
class SyncController < ApplicationController
  rate_limit to: 6, within: 1.minute, only: [:create]

  before_action :redirect_if_syncing, only: [:new, :create]
  before_action -> { redirect_if_not_syncing(new_sync_device_path) }, only: [:show]

  layout "page"

  def new
    @account = Account.new
  end

  def create
    if Current.challenge.validate(challenge_params[:challenge_solution])
      @account = Account.create
      self.current_account = @account.id

      redirect_to sync_path, notice: "Sync key generated"
    else
      @account = Account.new
      @account.errors.add(:base, "Incorrect solution. Try again?")
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @account = Current.account
  end

  private

  def challenge_params
    params.require(:account).permit(:challenge_solution)
  end
end

app/views/sync/device/new.html.erb
<% 
@page_title = "Sync your data with the cloud &nbsp;☁️✨"
%>

<% content_for :title do %>Sync your data<% end %>

<section>
  <div class="prose">
    <span>
      <p>Enable crossword data syncing with the cloud <span class="emoji">☁️</span> by entering your unique sync key below.</p>
    </span>
    <p class="highlight"><span><span class="emoji">🔑</span> <em>Don't have a sync key? <%= link_to tag.strong("Generate one now!"), new_sync_path %></em></span></p>
  </div>
</section>

<section>
  <%= form_with model: @account, url: sync_device_path, method: :post, class: "form" do |form| %>
    <%= form_errors @account.errors %>
    
    <div class="form-field">
      <%= form.label :key do %>
        Your sync key
      <% end %>
      <%= form.text_field :key, placeholder: "I.e. curious-german-jellyfish-farmer" %>
    </div>
    
    <div class="form-actions">
      <%= button "Enable syncing", icon: :arrow_down_up, type: :submit, theme: :primary %>
    </div>
  <% end %>
</section>

<footer class="prose centered">
  <p><em>Don't have a sync key? <%= link_to "Generate one now!", new_sync_path, "@click.prevent": "hijax" %></em></p>
  <p style="opacity: 0.7">&larr; <%= back_to_crosswords_link %></p>
</footer>