config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", :as => :rails_health_check

  root "crosswords#index"

  get "/:number", to: "crosswords#show", as: :crossword, constraints: {number: /\d.+/}

  get "/about", to: "pages#about", as: :about_page
  get "/settings", to: "pages#settings", as: :settings_page

  resource "sync", only: [:new, :create, :show], controller: :sync, as: :sync do
    resource :device, only: [:create, :destroy], controller: "sync/device", as: :device
  end
  get "/sync/device", to: "sync/device#new", as: :new_sync_device

  resources :answers, only: [:update]

  mount MissionControl::Jobs::Engine, at: "/jobs"

  namespace :admin do
    resources :crosswords
    resources :answers
    resources :accounts
    resources :imports

    root to: "crosswords#index"
  end

  resource :devmode, only: [:show, :destroy], controller: :devmode

  match "*unmatched", to: "application#not_found", via: :all
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%== "#{content_for(:title)} | " if content_for?(:title) %>crosswords.lol</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= javascript_include_tag "application", defer: true %>
    <%= stylesheet_link_tag :application %>
  </head>
  <body data-syncing="<%= syncing? %>">
    <div
      class="app"
      x-data="app"
      @popstate.window="loadPage(location)">
      <div
        class="loading-bar"
        x-data="loadingBar"
        :class="{loading: state === 'loading', loaded: state === 'complete'}">
        <div class="loading-bar-progress" :style="`width: ${progress}%`"></div>
      </div>
      <div data-morph-root>
        <header class="app-header">
          <div class="app-header-container">
            <%= link_to crossword_path(Crossword.latest), class: "app-header-branding", "@click.prevent": "hijax" do %>
              <%= image_tag "icon.svg", class: "app-header-logo", alt: "Logo for Crosswords.lol" %>
              <span class="app-header-name">crosswords.lol</span>
            <% end %>
            
            <div class="app-header-nav">
              <%=
                if devmode?
                  button_to devmode_path, method: :delete, id: "app-header-devmode-off" do
                    button :bug_off, tag_name: :span, alt: "Devmode off"
                  end
                end
              %>

              <%= button :calendar_1,
                href: crossword_path(Crossword.latest),
                alt: "Today's crossword",
                id: "app-header-latest-link",
                "@click.prevent": "hijax",
                class: {active: current_page?(crossword_path(Crossword.latest))} %>

              <%= button :circle_help,
                href: about_page_path,
                alt: "About",
                id: "app-header-about-link",
                "@click.prevent": "hijax",
                class: {active: current_page?(about_page_path)} %>

              <%= button :arrow_down_up,
                href: syncing? ? sync_path : new_sync_path(challenge: params[:challenge]),
                alt: "Sync",
                id: "app-header-sync-link",
                "@click.prevent": "hijax",
                class: {active: [new_sync_path, new_sync_device_path, sync_path].include?(url_for)} %>

              <%= button :settings,
                href: settings_page_path,
                alt: "Settings",
                id: "app-header-settings-link",
                "@click.prevent": "hijax",
                class: {active: current_page?(settings_page_path)} %>
            </div>
          </div>
        </header>
        <%= content_for?(:main) ? yield(:main) : yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/page.html.erb
<% 
page_id = url_for.delete_prefix("/")
%>

<% content_for :main do %>
  <div class="page" data-page-id="<%= page_id %>">
    <div class="page-container">
      <div class="page-body">
        <div class="page-bg"></div>
        <% if @page_title %>
          <header class="page-header">
            <h2 class="page-title"><%== @page_title %></h2>
          </header>
        <% end %>
        <div class="page-content">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<%= render template: "layouts/application" %>